services:
  - type: web
    name: stock-picker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: POLYGON_API_KEY
        sync: false
